# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class PyProgramChecker:
    def compile_from_source(self, source_filepath:str) -> PyProgramChecker:
        ...

    def execute(self) -> int:
        ...


