# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

class PyPotatoCPUTester:
    @classmethod
    def compile_from_source(cls, source_filepath:builtins.str) -> PyPotatoCPUTester: ...
    def execute(self) -> builtins.int: ...

